import { Anticipo } from '../anticipo/anticipo.model';
import { Cama } from '../cama/cama.model';
import { CargoAutomatico } from '../cargo-automatico/cargo-automatico.model';
import { CargosPendientes } from '../cargos-pendientes/cargos-pendientes.model';
import { CensoHistorico } from '../censo-historico/censo-historico.model';
import { Ciudad } from '../ciudad/ciudad.model';
import { ConcatenaConceptoPorCentroCosto } from '../concatena-concepto-por-centro-costo/concatena-concepto-por-centro-costo.model';
import { EncabezadoResultado } from '../encabezado-resultado/encabezado-resultado.model';
import { EntidadAdmision } from '../entidad-admision/entidad-admision.model';
import { ExcepcionRegargo } from '../excepcion-regargo/excepcion-regargo.model';
import { HomologacionServiciosAgfa } from '../homologacion-servicios-agfa/homologacion-servicios-agfa.model';
import { LoginSucursal } from '../login-sucursal/login-sucursal.model';
import { MedicamentoAltoCosto } from '../medicamento-alto-costo/medicamento-alto-costo.model';
import { MedicoGrupoProcedimiento } from '../medico-grupo-procedimiento/medico-grupo-procedimiento.model';
import { NumeroSecuencia } from '../numero-secuencia/numero-secuencia.model';
import { Prestador } from '../prestador/prestador.model';
import { ProcedimientoCentroCosto } from '../procedimiento-centro-costo/procedimiento-centro-costo.model';
import { RecalculoAutomatico } from '../recalculo-automatico/recalculo-automatico.model';
import { Salas } from '../salas/salas.model';
import { SucursalEntidad } from '../sucursal-entidad/sucursal-entidad.model';
import { TrazabilidadAdmision } from '../trazabilidad-admision/trazabilidad-admision.model';
import { ZonaHorariaVerano } from '../zona-horaria-verano/zona-horaria-verano.model';
import { CensoServicio } from '../censo-servicio/censo-servicio.model';
import { CitaRetraso } from '../cita-retraso/cita-retraso.model';
import { Consultorio } from '../consultorio/consultorio.model';
import { Entidad } from '../entidad/entidad.model';
import { GrupoEtareo } from '../grupo-etareo/grupo-etareo.model';
import { Login } from '../login/login.model';
import { Pedidos } from '../pedidos/pedidos.model';
import { ProcedimientoNivel } from '../procedimiento-nivel/procedimiento-nivel.model';
import { Seccion } from '../seccion/seccion.model';
import { Triage } from '../triage/triage.model';
import { ZonaHoraria } from '../zona-horaria/zona-horaria.model';

export interface Sucursal {
  _id?: string;
  codSucur: String;
  manCarAutUrg: String;
  manPrecargos: String;
  modFecAdm: String;
  anulSinvalidar: String;
  manProtocolos: String;
  codigorips: String;
  email: String;
  agfa: String;
  salMinLeg: Number;
  agfaMerge: String;
  manCarAutCe: String;
  director: String;
  difhorservidor: Number;
  agfaMediweb: String;
  manCamPla: String;
  consecutivoNn: Number;
  codGrabacionCt: String;
  ordenarGenerico: String;
  itemListaUnidadMedidaTiempoObservacion: Number;
  consecutivoMenorEdad: Number;
  conAutoriza: Number;
  pedidoManual: String;
  tieEspOb: Number;
  fax: String;
  incPedIntefaceAct: String;
  manUniAtePri: String;
  manRecAut: String;
  telefono: String;
  devIntefaceAct: String;
  manEnfermeria: String;
  conFormulacion: Number;
  direccion: String;
  pedIntefaceAct: String;
  phd: String;
  conForProc: Number;
  nivInstituc: Number;
  anulPedIntefaceAct: String;
  emailCtc: String;
  bloqPedidos: String;
  numConsult: Number;
  conCita: Number;
  pideCtc: String;
  manInventario: String;
  manTriage: String;
  manConvemed: String;
  manCitaesp: String;
  conProgciru: Number;
  numDoc: String;
  conCertifihos: Number;
  manDigiturno: String;
  conCertifisoat: Number;
  conAutRem: Number;
  horMedioDia: Number;
  manWscitas: String;
  conDietas: Number;
  descripcion: String;
  conRips: Number;
  manEstadoPac: String;
  fechaRegistro: Date;
  codInterno: String;
  manRedondeo: String;
  sucursalOsi: String;
  conCtacobro: Number;
  itemListaTipoDocumento: Number;
  observaciones: String;
  flagCenso: Boolean;
  loginRegistro: String;
  vlrRedondeo: Number;
  manConsAut: String;

  /** Many-To-One Relationships */
  
  idCiudad?: String;
  ciudad?: Ciudad;

  idPrestador?: String;
  prestador?: Prestador;

  idEntidad?: String;
  entidad?: Entidad;

  /** One-To-Many Relationships */
  anticipos?: Anticipo[];
  camas?: Cama[];
  cargoAutomaticos?: CargoAutomatico[];
  cargosPendientess?: CargosPendientes[];
  censoHistoricos?: CensoHistorico[];
  concatenaConceptoPorCentroCostos?: ConcatenaConceptoPorCentroCosto[];
  encabezadoResultados?: EncabezadoResultado[];
  entidadAdmisions?: EntidadAdmision[];
  excepcionRegargos?: ExcepcionRegargo[];
  homologacionServiciosAgfas?: HomologacionServiciosAgfa[];
  loginSucursals?: LoginSucursal[];
  medicamentoAltoCostos?: MedicamentoAltoCosto[];
  medicoGrupoProcedimientos?: MedicoGrupoProcedimiento[];
  numeroSecuencias?: NumeroSecuencia[];
  procedimientoCentroCostos?: ProcedimientoCentroCosto[];
  recalculoAutomaticos?: RecalculoAutomatico[];
  salass?: Salas[];
  sucursalEntidads?: SucursalEntidad[];
  trazabilidadAdmisions?: TrazabilidadAdmision[];
  zonaHorariaVeranos?: ZonaHorariaVerano[];
  censoServicios?: CensoServicio[];
  citaRetrasos?: CitaRetraso[];
  consultorios?: Consultorio[];
  grupoEtareos?: GrupoEtareo[];
  logins?: Login[];
  pedidoss?: Pedidos[];
  procedimientoNivels?: ProcedimientoNivel[];
  seccions?: Seccion[];
  triages?: Triage[];
  zonaHorarias?: ZonaHoraria[];
}
