const express = require('express');
const path = require('path');
const logger = require('morgan');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const fallback = require('express-history-api-fallback');
const config = require('./server-config');
const mongoose = require('mongoose');

mongoose.Promise = Promise;

mongoose.connect(config.mongo.uri, { useMongoClient: true });

mongoose.connection.on('connected', () => {
    console.log(`Connected to database`);
});

mongoose.connection.on('error', (err) => {
    console.log(`Database Error: ${err}`);
});

const app = express();
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
const root = path.join(__dirname, 'dist');
app.use(express.static(root));

// api routes
const admisionObservaciones = require('./server/api/admision-observaciones');
const aliasTipoDocumento = require('./server/api/alias-tipo-documento');
const anticipo = require('./server/api/anticipo');
const auditoria = require('./server/api/auditoria');
const auditoriaContrato = require('./server/api/auditoria-contrato');
const auditoriaEstadoAdmision = require('./server/api/auditoria-estado-admision');
const auditoriaSolicitud = require('./server/api/auditoria-solicitud');
const autorizacionBh = require('./server/api/autorizacion-bh');
const calendario = require('./server/api/calendario');
const cama = require('./server/api/cama');
const camaPlan = require('./server/api/cama-plan');
const cargoAutomatico = require('./server/api/cargo-automatico');
const cargosPendientes = require('./server/api/cargos-pendientes');
const carnet = require('./server/api/carnet');
const catalogoMedicamentos = require('./server/api/catalogo-medicamentos');
const catalogoMedicamentosDetalle = require('./server/api/catalogo-medicamentos-detalle');
const censoHistorico = require('./server/api/censo-historico');
const censoServicio = require('./server/api/censo-servicio');
const censoTraslado = require('./server/api/censo-traslado');
const centroCostoValido = require('./server/api/centro-costo-valido');
const citaRetraso = require('./server/api/cita-retraso');
const ciudad = require('./server/api/ciudad');
const codigoDia = require('./server/api/codigo-dia');
const codigoPostal = require('./server/api/codigo-postal');
const concatenaConceptoPorCentroCosto = require('./server/api/concatena-concepto-por-centro-costo');
const consultaExternaPyp = require('./server/api/consulta-externa-pyp');
const consultorio = require('./server/api/consultorio');
const consumoSoatOtraIps = require('./server/api/consumo-soat-otra-ips');
const detalleCargosPendientes = require('./server/api/detalle-cargos-pendientes');
const diagnostico = require('./server/api/diagnostico');
const encabezadoCatalogo = require('./server/api/encabezado-catalogo');
const encabezadoResultado = require('./server/api/encabezado-resultado');
const entidad = require('./server/api/entidad');
const entidadAdmision = require('./server/api/entidad-admision');
const entidadUvr = require('./server/api/entidad-uvr');
const epsRecobrable = require('./server/api/eps-recobrable');
const estadoSalidaPaciente = require('./server/api/estado-salida-paciente');
const excepcionProducto = require('./server/api/excepcion-producto');
const excepcionRegargo = require('./server/api/excepcion-regargo');
const fotoEstadoCama = require('./server/api/foto-estado-cama');
const grupoEtareo = require('./server/api/grupo-etareo');
const grupoProcedimiento = require('./server/api/grupo-procedimiento');
const homologacionEntidad = require('./server/api/homologacion-entidad');
const homologacionServiciosAgfa = require('./server/api/homologacion-servicios-agfa');
const institucion = require('./server/api/institucion');
const localidad = require('./server/api/localidad');
const login = require('./server/api/login');
const loginSucursal = require('./server/api/login-sucursal');
const medicamentoAltoCosto = require('./server/api/medicamento-alto-costo');
const medicoGrupoProcedimiento = require('./server/api/medico-grupo-procedimiento');
const medicoSucursal = require('./server/api/medico-sucursal');
const medicoSucursalEntidad = require('./server/api/medico-sucursal-entidad');
const moneda = require('./server/api/moneda');
const motivo = require('./server/api/motivo');
const nivelCargo = require('./server/api/nivel-cargo');
const numeroSecuencia = require('./server/api/numero-secuencia');
const ocupacion = require('./server/api/ocupacion');
const opcion = require('./server/api/opcion');
const pacienteInconsistencias = require('./server/api/paciente-inconsistencias');
const pais = require('./server/api/pais');
const parAliascolumnas = require('./server/api/par-aliascolumnas');
const parDependenciaCampo = require('./server/api/par-dependencia-campo');
const parFormatoCampo = require('./server/api/par-formato-campo');
const parFormulario = require('./server/api/par-formulario');
const parOrigenInformacion = require('./server/api/par-origen-informacion');
const parTipoCampo = require('./server/api/par-tipo-campo');
const pedidos = require('./server/api/pedidos');
const planes = require('./server/api/planes');
const porcentajeMedico = require('./server/api/porcentaje-medico');
const prefijo = require('./server/api/prefijo');
const prestador = require('./server/api/prestador');
const prestadorCentroCostoUnico = require('./server/api/prestador-centro-costo-unico');
const prioridad = require('./server/api/prioridad');
const procedimiento = require('./server/api/procedimiento');
const procedimientoCentroCosto = require('./server/api/procedimiento-centro-costo');
const procedimientoConvenioCapitado = require('./server/api/procedimiento-convenio-capitado');
const procedimientoEntidad = require('./server/api/procedimiento-entidad');
const procedimientoFinalidad = require('./server/api/procedimiento-finalidad');
const procedimientoNivel = require('./server/api/procedimiento-nivel');
const procedimientosRis = require('./server/api/procedimientos-ris');
const producto = require('./server/api/producto');
const pypProcedimientoPrograma = require('./server/api/pyp-procedimiento-programa');
const pypProgramas = require('./server/api/pyp-programas');
const recalculoAutomatico = require('./server/api/recalculo-automatico');
const recargo = require('./server/api/recargo');
const recargoAutomatico = require('./server/api/recargo-automatico');
const religion = require('./server/api/religion');
const rutaLiquidacion = require('./server/api/ruta-liquidacion');
const salario = require('./server/api/salario');
const salas = require('./server/api/salas');
const seccion = require('./server/api/seccion');
const subGrupoProcedimiento = require('./server/api/sub-grupo-procedimiento');
const subconcepto = require('./server/api/subconcepto');
const sucursal = require('./server/api/sucursal');
const sucursalCentroCosto = require('./server/api/sucursal-centro-costo');
const sucursalEntidad = require('./server/api/sucursal-entidad');
const sustitutos = require('./server/api/sustitutos');
const tarifaVacunacion = require('./server/api/tarifa-vacunacion');
const tiempoRecargo = require('./server/api/tiempo-recargo');
const tipoAdmision = require('./server/api/tipo-admision');
const tipoAfiliado = require('./server/api/tipo-afiliado');
const tipoAnestesia = require('./server/api/tipo-anestesia');
const tipoCama = require('./server/api/tipo-cama');
const tipoCirugia = require('./server/api/tipo-cirugia');
const tipoEntidadLaboratorio = require('./server/api/tipo-entidad-laboratorio');
const tipoMotivo = require('./server/api/tipo-motivo');
const tipoNovedad = require('./server/api/tipo-novedad');
const tipoPlan = require('./server/api/tipo-plan');
const tipoTarifaVacunacion = require('./server/api/tipo-tarifa-vacunacion');
const tiposDocumentoEntidad = require('./server/api/tipos-documento-entidad');
const tiposValores = require('./server/api/tipos-valores');
const trazabilidadAdmision = require('./server/api/trazabilidad-admision');
const trazabilidadAdmisionCargos = require('./server/api/trazabilidad-admision-cargos');
const trazabilidadAdmisionListaEsperaHistoriaClinica = require('./server/api/trazabilidad-admision-lista-espera-historia-clinica');
const triage = require('./server/api/triage');
const unidadMedidaPedido = require('./server/api/unidad-medida-pedido');
const vacunas = require('./server/api/vacunas');
const valeElectronico = require('./server/api/vale-electronico');
const zonaHoraria = require('./server/api/zona-horaria');
const zonaHorariaVerano = require('./server/api/zona-horaria-verano');

app.use('/api/admision-observacioness', admisionObservaciones);
app.use('/api/alias-tipo-documentos', aliasTipoDocumento);
app.use('/api/anticipos', anticipo);
app.use('/api/auditorias', auditoria);
app.use('/api/auditoria-contratos', auditoriaContrato);
app.use('/api/auditoria-estado-admisions', auditoriaEstadoAdmision);
app.use('/api/auditoria-solicituds', auditoriaSolicitud);
app.use('/api/autorizacion-bhs', autorizacionBh);
app.use('/api/calendarios', calendario);
app.use('/api/camas', cama);
app.use('/api/cama-plans', camaPlan);
app.use('/api/cargo-automaticos', cargoAutomatico);
app.use('/api/cargos-pendientess', cargosPendientes);
app.use('/api/carnets', carnet);
app.use('/api/catalogo-medicamentoss', catalogoMedicamentos);
app.use('/api/catalogo-medicamentos-detalles', catalogoMedicamentosDetalle);
app.use('/api/censo-historicos', censoHistorico);
app.use('/api/censo-servicios', censoServicio);
app.use('/api/censo-traslados', censoTraslado);
app.use('/api/centro-costo-validos', centroCostoValido);
app.use('/api/cita-retrasos', citaRetraso);
app.use('/api/ciudads', ciudad);
app.use('/api/codigo-dias', codigoDia);
app.use('/api/codigo-postals', codigoPostal);
app.use('/api/concatena-concepto-por-centro-costos', concatenaConceptoPorCentroCosto);
app.use('/api/consulta-externa-pyps', consultaExternaPyp);
app.use('/api/consultorios', consultorio);
app.use('/api/consumo-soat-otra-ipss', consumoSoatOtraIps);
app.use('/api/detalle-cargos-pendientess', detalleCargosPendientes);
app.use('/api/diagnosticos', diagnostico);
app.use('/api/encabezado-catalogos', encabezadoCatalogo);
app.use('/api/encabezado-resultados', encabezadoResultado);
app.use('/api/entidads', entidad);
app.use('/api/entidad-admisions', entidadAdmision);
app.use('/api/entidad-uvrs', entidadUvr);
app.use('/api/eps-recobrables', epsRecobrable);
app.use('/api/estado-salida-pacientes', estadoSalidaPaciente);
app.use('/api/excepcion-productos', excepcionProducto);
app.use('/api/excepcion-regargos', excepcionRegargo);
app.use('/api/foto-estado-camas', fotoEstadoCama);
app.use('/api/grupo-etareos', grupoEtareo);
app.use('/api/grupo-procedimientos', grupoProcedimiento);
app.use('/api/homologacion-entidads', homologacionEntidad);
app.use('/api/homologacion-servicios-agfas', homologacionServiciosAgfa);
app.use('/api/institucions', institucion);
app.use('/api/localidads', localidad);
app.use('/api/logins', login);
app.use('/api/login-sucursals', loginSucursal);
app.use('/api/medicamento-alto-costos', medicamentoAltoCosto);
app.use('/api/medico-grupo-procedimientos', medicoGrupoProcedimiento);
app.use('/api/medico-sucursals', medicoSucursal);
app.use('/api/medico-sucursal-entidads', medicoSucursalEntidad);
app.use('/api/monedas', moneda);
app.use('/api/motivos', motivo);
app.use('/api/nivel-cargos', nivelCargo);
app.use('/api/numero-secuencias', numeroSecuencia);
app.use('/api/ocupacions', ocupacion);
app.use('/api/opcions', opcion);
app.use('/api/paciente-inconsistenciass', pacienteInconsistencias);
app.use('/api/paiss', pais);
app.use('/api/par-aliascolumnass', parAliascolumnas);
app.use('/api/par-dependencia-campos', parDependenciaCampo);
app.use('/api/par-formato-campos', parFormatoCampo);
app.use('/api/par-formularios', parFormulario);
app.use('/api/par-origen-informacions', parOrigenInformacion);
app.use('/api/par-tipo-campos', parTipoCampo);
app.use('/api/pedidoss', pedidos);
app.use('/api/planess', planes);
app.use('/api/porcentaje-medicos', porcentajeMedico);
app.use('/api/prefijos', prefijo);
app.use('/api/prestadors', prestador);
app.use('/api/prestador-centro-costo-unicos', prestadorCentroCostoUnico);
app.use('/api/prioridads', prioridad);
app.use('/api/procedimientos', procedimiento);
app.use('/api/procedimiento-centro-costos', procedimientoCentroCosto);
app.use('/api/procedimiento-convenio-capitados', procedimientoConvenioCapitado);
app.use('/api/procedimiento-entidads', procedimientoEntidad);
app.use('/api/procedimiento-finalidads', procedimientoFinalidad);
app.use('/api/procedimiento-nivels', procedimientoNivel);
app.use('/api/procedimientos-riss', procedimientosRis);
app.use('/api/productos', producto);
app.use('/api/pyp-procedimiento-programas', pypProcedimientoPrograma);
app.use('/api/pyp-programass', pypProgramas);
app.use('/api/recalculo-automaticos', recalculoAutomatico);
app.use('/api/recargos', recargo);
app.use('/api/recargo-automaticos', recargoAutomatico);
app.use('/api/religions', religion);
app.use('/api/ruta-liquidacions', rutaLiquidacion);
app.use('/api/salarios', salario);
app.use('/api/salass', salas);
app.use('/api/seccions', seccion);
app.use('/api/sub-grupo-procedimientos', subGrupoProcedimiento);
app.use('/api/subconceptos', subconcepto);
app.use('/api/sucursals', sucursal);
app.use('/api/sucursal-centro-costos', sucursalCentroCosto);
app.use('/api/sucursal-entidads', sucursalEntidad);
app.use('/api/sustitutoss', sustitutos);
app.use('/api/tarifa-vacunacions', tarifaVacunacion);
app.use('/api/tiempo-recargos', tiempoRecargo);
app.use('/api/tipo-admisions', tipoAdmision);
app.use('/api/tipo-afiliados', tipoAfiliado);
app.use('/api/tipo-anestesias', tipoAnestesia);
app.use('/api/tipo-camas', tipoCama);
app.use('/api/tipo-cirugias', tipoCirugia);
app.use('/api/tipo-entidad-laboratorios', tipoEntidadLaboratorio);
app.use('/api/tipo-motivos', tipoMotivo);
app.use('/api/tipo-novedads', tipoNovedad);
app.use('/api/tipo-plans', tipoPlan);
app.use('/api/tipo-tarifa-vacunacions', tipoTarifaVacunacion);
app.use('/api/tipos-documento-entidads', tiposDocumentoEntidad);
app.use('/api/tipos-valoress', tiposValores);
app.use('/api/trazabilidad-admisions', trazabilidadAdmision);
app.use('/api/trazabilidad-admision-cargoss', trazabilidadAdmisionCargos);
app.use('/api/trazabilidad-admision-lista-espera-historia-clinicas', trazabilidadAdmisionListaEsperaHistoriaClinica);
app.use('/api/triages', triage);
app.use('/api/unidad-medida-pedidos', unidadMedidaPedido);
app.use('/api/vacunass', vacunas);
app.use('/api/vale-electronicos', valeElectronico);
app.use('/api/zona-horarias', zonaHoraria);
app.use('/api/zona-horaria-veranos', zonaHorariaVerano);

app.use(fallback('index.html', { root }));
app.get('*', (req, res) => {
  res.send(path.join(__dirname, 'dist/index.html'));
});
// catch 404 and forward to error handler
app.use((req, res, next) => {
  const err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use((err, req, res, next) => {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.json({ error: 'error'});
});

module.exports = app;
