import { Anticipo } from '../anticipo/anticipo.model';
import { AuditoriaContrato } from '../auditoria-contrato/auditoria-contrato.model';
import { CamaPlan } from '../cama-plan/cama-plan.model';
import { CargoAutomatico } from '../cargo-automatico/cargo-automatico.model';
import { CargosPendientes } from '../cargos-pendientes/cargos-pendientes.model';
import { CitaRetraso } from '../cita-retraso/cita-retraso.model';
import { Ciudad } from '../ciudad/ciudad.model';
import { DetalleCargosPendientes } from '../detalle-cargos-pendientes/detalle-cargos-pendientes.model';
import { EntidadUvr } from '../entidad-uvr/entidad-uvr.model';
import { EpsRecobrable } from '../eps-recobrable/eps-recobrable.model';
import { ExcepcionRegargo } from '../excepcion-regargo/excepcion-regargo.model';
import { HomologacionServiciosAgfa } from '../homologacion-servicios-agfa/homologacion-servicios-agfa.model';
import { PacienteInconsistencias } from '../paciente-inconsistencias/paciente-inconsistencias.model';
import { ProcedimientoEntidad } from '../procedimiento-entidad/procedimiento-entidad.model';
import { RecalculoAutomatico } from '../recalculo-automatico/recalculo-automatico.model';
import { Sucursal } from '../sucursal/sucursal.model';
import { SucursalEntidad } from '../sucursal-entidad/sucursal-entidad.model';
import { TipoCirugia } from '../tipo-cirugia/tipo-cirugia.model';
import { TipoPlan } from '../tipo-plan/tipo-plan.model';
import { EntidadAdmision } from '../entidad-admision/entidad-admision.model';
import { ExcepcionProducto } from '../excepcion-producto/excepcion-producto.model';
import { GrupoEtareo } from '../grupo-etareo/grupo-etareo.model';
import { HomologacionEntidad } from '../homologacion-entidad/homologacion-entidad.model';
import { MedicamentoAltoCosto } from '../medicamento-alto-costo/medicamento-alto-costo.model';
import { Planes } from '../planes/planes.model';
import { RecargoAutomatico } from '../recargo-automatico/recargo-automatico.model';
import { TiposDocumentoEntidad } from '../tipos-documento-entidad/tipos-documento-entidad.model';
import { Triage } from '../triage/triage.model';

export interface Entidad {
  _id?: string;
  entidad: String;
  tiempoCubVez: Number;
  codInterno: String;
  tiempoCubExt: Number;
  topLiqCirugia: Number;
  tiempoCubUrg: Number;
  codBarrasCarnet: String;
  manejaCopago: String;
  manCapitacionodo: String;
  manejaRecaudo: String;
  tiempoObserva: Number;
  codBarrDigCtrl: String;
  observaciones: String;
  direccion: String;
  pedAutoriza: String;
  tiempoCubOdontologico: Number;
  loginRegistro: String;
  fax: String;
  conSinConv: String;
  itemListaUnidadMedidaOdontologia: Number;
  fechaRegistro: Date;
  telefono: String;
  valorMaximoLiquidacion: Number;
  manprogcronicos: String;
  vlrTopPor: Number;
  responsable: String;
  valorMinimoLiquidacion: Number;
  maxentregasformulacronicos: Number;
  manTopPor: String;
  numDoc: String;
  manejaPorcentajeIncremento: Number;
  email: String;
  manTopes: String;
  descripcion: String;
  fechaConvenio: Date;
  manWebNuevo: String;
  montoxproce: String;
  itemListaUnidadMedidaObservacion: Number;
  dirIpEntidad: String;
  manCita: String;
  entidadOsi: String;
  itemListaUnidadMedidaPrimeraVez: Number;
  manejaMedFamiliar: String;
  manejaProteccionDatos: String;
  caduForProcedqx: Number;
  itemListaUnidadMedidaExterna: Number;
  manejaCapitacion: String;
  cargos: String;
  caduForMedicame: Number;
  itemListaUnidadMedidaUrgencia: Number;
  manejaCorteAnual: String;
  noCargos: Number;
  caduForProced: Number;
  confirmacionManual: String;
  pedAutMedicame: String;
  manPaqNoQuirur: String;
  manConvMed: String;
  itemListaTipoUsuario: Number;
  nroMedFor: Number;
  convenioInter: String;
  bdEstadoExt: String;
  itemListaTipoDocumento: Number;
  manejaCorte: String;
  planobh: String;
  nivValPrimeravez: String;
  itemListaTipoEntidad: Number;
  numDiascalend: Number;
  manNuevaAfiliacion: String;
  numCortesMes: Number;
  verEstadoPac: String;
  codBarrasDoc: String;

  /** Many-To-One Relationships */
  
  idCiudad?: String;
  ciudad?: Ciudad;

  /** One-To-Many Relationships */
  anticipos?: Anticipo[];
  auditoriaContratos?: AuditoriaContrato[];
  camaPlans?: CamaPlan[];
  cargoAutomaticos?: CargoAutomatico[];
  cargosPendientess?: CargosPendientes[];
  citaRetrasos?: CitaRetraso[];
  detalleCargosPendientess?: DetalleCargosPendientes[];
  entidadUvrs?: EntidadUvr[];
  epsRecobrables?: EpsRecobrable[];
  excepcionRegargos?: ExcepcionRegargo[];
  homologacionServiciosAgfas?: HomologacionServiciosAgfa[];
  pacienteInconsistenciass?: PacienteInconsistencias[];
  procedimientoEntidads?: ProcedimientoEntidad[];
  recalculoAutomaticos?: RecalculoAutomatico[];
  sucursals?: Sucursal[];
  sucursalEntidads?: SucursalEntidad[];
  tipoCirugias?: TipoCirugia[];
  tipoPlans?: TipoPlan[];
  entidadAdmisions?: EntidadAdmision[];
  excepcionProductos?: ExcepcionProducto[];
  grupoEtareos?: GrupoEtareo[];
  homologacionEntidads?: HomologacionEntidad[];
  homologacionEntidad1s?: HomologacionEntidad[];
  medicamentoAltoCostos?: MedicamentoAltoCosto[];
  planess?: Planes[];
  recargoAutomaticos?: RecargoAutomatico[];
  tiposDocumentoEntidads?: TiposDocumentoEntidad[];
  triages?: Triage[];
}
